/* ==================== Celebrity Face Types ==================== */

export interface Celebrity {
  id: string;
  name: string;
  group: string;
  gender: "male" | "female";
  category: "idol" | "actor";
  keywords: string[];
  features: {
    eyes: string;
    nose: string;
    lips: string;
    faceShape: string;
  };
  imageEmoji: string;
}

export interface CelebrityMatch {
  celebrityId: string;
  percentage: number;
  appealPoint?: string;
}

export interface CelebrityAnalysisResult {
  gender: "male" | "female";
  sameGenderTop5: CelebrityMatch[];
  oppositeGenderTop2: CelebrityMatch[];
  faceAnalysis: {
    eyes: string;
    nose: string;
    lips: string;
    faceShape: string;
  };
  overallVibe: string[];
  styleRecommendation: {
    makeup: string;
    hair: string;
    fashion: string;
  };
  uniqueRate: number;
  aiComment: string;
}

export const celebrities: Record<string, Celebrity> = {
  /* ===== Female Idols (24) ===== */
  karina: {
    id: "karina",
    name: "카리나",
    group: "에스파",
    gender: "female",
    category: "idol",
    keywords: ["고양이상", "시크", "차가운 매력", "완벽한 비율"],
    features: { eyes: "고양이눈", nose: "높은 콧대", lips: "얇은 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🐱",
  },
  winter: {
    id: "winter",
    name: "윈터",
    group: "에스파",
    gender: "female",
    category: "idol",
    keywords: ["차가운 미모", "얼음공주", "날카로운 이목구비"],
    features: { eyes: "날카로운 눈매", nose: "오똑한 코", lips: "작은 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "❄️",
  },
  jennie: {
    id: "jennie",
    name: "제니",
    group: "블랙핑크",
    gender: "female",
    category: "idol",
    keywords: ["인간 샤넬", "통통한 볼", "매력적인 눈"],
    features: { eyes: "무쌍 매력", nose: "작은 코", lips: "도톰한 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🖤",
  },
  jisoo: {
    id: "jisoo",
    name: "지수",
    group: "블랙핑크",
    gender: "female",
    category: "idol",
    keywords: ["한국 미인", "단아함", "청순", "고전미"],
    features: { eyes: "또렷한 쌍꺼풀", nose: "오똑한 코", lips: "도톰한 입술", faceShape: "계란형" },
    imageEmoji: "🌸",
  },
  rose: {
    id: "rose",
    name: "로제",
    group: "블랙핑크",
    gender: "female",
    category: "idol",
    keywords: ["인형 비주얼", "마른 체형", "독특한 음색"],
    features: { eyes: "큰 눈", nose: "높은 콧대", lips: "얇은 입술", faceShape: "작은 갸름한 얼굴" },
    imageEmoji: "🌹",
  },
  lisa: {
    id: "lisa",
    name: "리사",
    group: "블랙핑크",
    gender: "female",
    category: "idol",
    keywords: ["이국적 매력", "인형 비주얼", "날카로운 턱선"],
    features: { eyes: "큰 눈", nose: "작은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "💃",
  },
  nayeon: {
    id: "nayeon",
    name: "나연",
    group: "트와이스",
    gender: "female",
    category: "idol",
    keywords: ["토끼상", "사랑스러운", "앞니 매력"],
    features: { eyes: "초승달 눈웃음", nose: "작은 코", lips: "토끼 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🐰",
  },
  sana: {
    id: "sana",
    name: "사나",
    group: "트와이스",
    gender: "female",
    category: "idol",
    keywords: ["매력적인 미소", "애교", "큐트"],
    features: { eyes: "웃는 눈", nose: "귀여운 코", lips: "하트 입술", faceShape: "부드러운 곡선" },
    imageEmoji: "💖",
  },
  tzuyu: {
    id: "tzuyu",
    name: "쯔위",
    group: "트와이스",
    gender: "female",
    category: "idol",
    keywords: ["이국적 미모", "인형", "완벽한 비율"],
    features: { eyes: "큰 또렷한 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 계란형" },
    imageEmoji: "👸",
  },
  anyujin: {
    id: "anyujin",
    name: "안유진",
    group: "아이브",
    gender: "female",
    category: "idol",
    keywords: ["청순", "건강미", "밝은 에너지"],
    features: { eyes: "큰 쌍꺼풀 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🌟",
  },
  jangwonyoung: {
    id: "jangwonyoung",
    name: "장원영",
    group: "아이브",
    gender: "female",
    category: "idol",
    keywords: ["인형 비주얼", "긴 다리", "공주"],
    features: { eyes: "큰 눈", nose: "오똑한 코", lips: "앵두 입술", faceShape: "작은 V라인" },
    imageEmoji: "👑",
  },
  minji: {
    id: "minji",
    name: "민지",
    group: "뉴진스",
    gender: "female",
    category: "idol",
    keywords: ["청량", "깨끗한 이미지", "걸크러쉬"],
    features: { eyes: "시원한 눈매", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "💎",
  },
  hanni: {
    id: "hanni",
    name: "하니",
    group: "뉴진스",
    gender: "female",
    category: "idol",
    keywords: ["귀여운", "호주 감성", "사랑스러운"],
    features: { eyes: "동그란 눈", nose: "작은 코", lips: "귀여운 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🧸",
  },
  haerin: {
    id: "haerin",
    name: "해린",
    group: "뉴진스",
    gender: "female",
    category: "idol",
    keywords: ["고양이상", "시크", "몽환적"],
    features: { eyes: "고양이 눈매", nose: "작은 코", lips: "얇은 입술", faceShape: "작은 갸름한 얼굴" },
    imageEmoji: "🐈",
  },
  irene: {
    id: "irene",
    name: "아이린",
    group: "레드벨벳",
    gender: "female",
    category: "idol",
    keywords: ["레전드 비주얼", "청순+섹시", "완벽한 얼굴"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 계란형" },
    imageEmoji: "🌺",
  },
  chuu: {
    id: "chuu",
    name: "츄",
    group: "이달의소녀",
    gender: "female",
    category: "idol",
    keywords: ["밝은 에너지", "사과 볼", "비타민"],
    features: { eyes: "반달 눈웃음", nose: "귀여운 코", lips: "하트 입술", faceShape: "동그란 볼" },
    imageEmoji: "🍎",
  },
  ryujin: {
    id: "ryujin",
    name: "류진",
    group: "있지",
    gender: "female",
    category: "idol",
    keywords: ["걸크러쉬", "카리스마", "시크"],
    features: { eyes: "날카로운 눈매", nose: "높은 콧대", lips: "도톰한 입술", faceShape: "각진 턱선" },
    imageEmoji: "🔥",
  },
  yeji: {
    id: "yeji",
    name: "예지",
    group: "있지",
    gender: "female",
    category: "idol",
    keywords: ["여우상", "이국적", "날카로운 이목구비"],
    features: { eyes: "여우 눈매", nose: "높은 코", lips: "얇은 입술", faceShape: "갸름한 V라인" },
    imageEmoji: "🦊",
  },
  miyeon: {
    id: "miyeon",
    name: "미연",
    group: "여자아이들",
    gender: "female",
    category: "idol",
    keywords: ["한국 미인", "단아함", "청순"],
    features: { eyes: "또렷한 눈", nose: "오똑한 코", lips: "자연스러운 입술", faceShape: "계란형" },
    imageEmoji: "🌷",
  },
  yuqi: {
    id: "yuqi",
    name: "우기",
    group: "여자아이들",
    gender: "female",
    category: "idol",
    keywords: ["허스키 음색", "귀여운", "통통 볼"],
    features: { eyes: "동그란 눈", nose: "귀여운 코", lips: "도톰한 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🐻",
  },
  sakura: {
    id: "sakura",
    name: "사쿠라",
    group: "르세라핌",
    gender: "female",
    category: "idol",
    keywords: ["인형", "일본 미인", "투명한 피부"],
    features: { eyes: "큰 눈", nose: "작은 코", lips: "얇은 입술", faceShape: "작은 동그란 얼굴" },
    imageEmoji: "🎀",
  },
  kazuha: {
    id: "kazuha",
    name: "카즈하",
    group: "르세라핌",
    gender: "female",
    category: "idol",
    keywords: ["발레리나", "우아함", "청순"],
    features: { eyes: "시원한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🩰",
  },
  huryunjin: {
    id: "huryunjin",
    name: "허윤진",
    group: "르세라핌",
    gender: "female",
    category: "idol",
    keywords: ["시크", "서양적 매력", "강렬한"],
    features: { eyes: "날카로운 눈매", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "🗽",
  },
  kimchaewon: {
    id: "kimchaewon",
    name: "김채원",
    group: "르세라핌",
    gender: "female",
    category: "idol",
    keywords: ["청순", "귀여운", "인형"],
    features: { eyes: "큰 눈", nose: "작은 코", lips: "앵두 입술", faceShape: "작은 동그란 얼굴" },
    imageEmoji: "🍒",
  },

  /* ===== Female Actors (15) ===== */
  iu: {
    id: "iu",
    name: "아이유",
    group: "솔로",
    gender: "female",
    category: "actor",
    keywords: ["국민 여동생", "청순", "맑은 이미지"],
    features: { eyes: "맑은 눈", nose: "작은 코", lips: "자연스러운 입술", faceShape: "작은 동그란 얼굴" },
    imageEmoji: "🎵",
  },
  suzy: {
    id: "suzy",
    name: "수지",
    group: "솔로",
    gender: "female",
    category: "actor",
    keywords: ["국민 첫사랑", "청순", "자연미인"],
    features: { eyes: "순수한 눈", nose: "자연스러운 코", lips: "도톰한 입술", faceShape: "계란형" },
    imageEmoji: "💝",
  },
  kimtaeri: {
    id: "kimtaeri",
    name: "김태리",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["지적 매력", "독보적 분위기", "청순+시크"],
    features: { eyes: "지적인 눈매", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "📚",
  },
  hansohee: {
    id: "hansohee",
    name: "한소희",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["신비로운", "차가운 미모", "독보적"],
    features: { eyes: "날카로운 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "🌙",
  },
  kimjiwon: {
    id: "kimjiwon",
    name: "김지원",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["청순", "단아함", "흰 피부"],
    features: { eyes: "순수한 눈", nose: "오똑한 코", lips: "자연스러운 입술", faceShape: "계란형" },
    imageEmoji: "🤍",
  },
  jeonjihyun: {
    id: "jeonjihyun",
    name: "전지현",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["여왕의 카리스마", "시크", "레전드 미모"],
    features: { eyes: "시크한 눈매", nose: "높은 콧대", lips: "도톰한 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🏰",
  },
  sonyejin: {
    id: "sonyejin",
    name: "손예진",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["따뜻한 미소", "자연미인", "로맨스 퀸"],
    features: { eyes: "따뜻한 눈", nose: "자연스러운 코", lips: "도톰한 입술", faceShape: "부드러운 곡선" },
    imageEmoji: "🌻",
  },
  songhyekyo: {
    id: "songhyekyo",
    name: "송혜교",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["동양적 미인", "고급스러운", "시간이 멈춘 미모"],
    features: { eyes: "깊은 눈", nose: "오똑한 코", lips: "도톰한 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "💫",
  },
  kimgoeun: {
    id: "kimgoeun",
    name: "김고은",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["맑은 피부", "순수", "밝은 에너지"],
    features: { eyes: "맑은 큰 눈", nose: "작은 코", lips: "자연스러운 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "✨",
  },
  parkboyoung: {
    id: "parkboyoung",
    name: "박보영",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["동안", "귀여운", "사랑스러운"],
    features: { eyes: "큰 눈", nose: "작은 코", lips: "귀여운 입술", faceShape: "작은 동그란 얼굴" },
    imageEmoji: "🧚",
  },
  shinsekyung: {
    id: "shinsekyung",
    name: "신세경",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["청순", "고전미", "깨끗한 이미지"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🌿",
  },
  leeseongkyoung: {
    id: "leeseongkyoung",
    name: "이성경",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["밝은 미소", "건강미", "긴 다리"],
    features: { eyes: "시원한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "작은 얼굴" },
    imageEmoji: "☀️",
  },
  parkminyoung: {
    id: "parkminyoung",
    name: "박민영",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["청순+섹시", "완벽한 비율", "로맨스 여왕"],
    features: { eyes: "큰 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "갸름한 V라인" },
    imageEmoji: "💗",
  },
  hanhyojoo: {
    id: "hanhyojoo",
    name: "한효주",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["밝은 미소", "청순", "자연미인"],
    features: { eyes: "눈웃음", nose: "자연스러운 코", lips: "따뜻한 미소", faceShape: "부드러운 곡선" },
    imageEmoji: "😊",
  },
  shinmina: {
    id: "shinmina",
    name: "신민아",
    group: "배우",
    gender: "female",
    category: "actor",
    keywords: ["긴 생머리", "청순", "여신"],
    features: { eyes: "맑은 눈", nose: "오똑한 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🧝‍♀️",
  },

  /* ===== Male Idols (20) ===== */
  v: {
    id: "v",
    name: "뷔",
    group: "BTS",
    gender: "male",
    category: "idol",
    keywords: ["세계적 미남", "조각 같은 이목구비", "독보적"],
    features: { eyes: "깊은 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "🎨",
  },
  jungkook: {
    id: "jungkook",
    name: "정국",
    group: "BTS",
    gender: "male",
    category: "idol",
    keywords: ["황금막내", "큰 눈", "사슴상"],
    features: { eyes: "큰 사슴 눈", nose: "오똑한 코", lips: "도톰한 입술", faceShape: "계란형" },
    imageEmoji: "🦌",
  },
  jimin: {
    id: "jimin",
    name: "지민",
    group: "BTS",
    gender: "male",
    category: "idol",
    keywords: ["여우상", "날카로운 눈매", "중성적 매력"],
    features: { eyes: "날카로운 여우눈", nose: "작은 코", lips: "도톰한 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🦊",
  },
  jin: {
    id: "jin",
    name: "진",
    group: "BTS",
    gender: "male",
    category: "idol",
    keywords: ["월드와이드 핸섬", "어깨깡패", "조각미남"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🌎",
  },
  chaeunwoo: {
    id: "chaeunwoo",
    name: "차은우",
    group: "아스트로",
    gender: "male",
    category: "idol",
    keywords: ["얼굴 천재", "조각미남", "완벽한 비율"],
    features: { eyes: "또렷한 쌍꺼풀", nose: "높은 콧대", lips: "자연스러운 입술", faceShape: "작은 V라인" },
    imageEmoji: "💎",
  },
  jaehyun: {
    id: "jaehyun",
    name: "재현",
    group: "NCT",
    gender: "male",
    category: "idol",
    keywords: ["비주얼 센터", "따뜻한 비주얼", "보조개"],
    features: { eyes: "따뜻한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "계란형" },
    imageEmoji: "🤎",
  },
  doyoung: {
    id: "doyoung",
    name: "도영",
    group: "NCT",
    gender: "male",
    category: "idol",
    keywords: ["토끼상", "지적 매력", "깔끔한"],
    features: { eyes: "또렷한 눈", nose: "오똑한 코", lips: "앵두 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🐰",
  },
  mark: {
    id: "mark",
    name: "마크",
    group: "NCT",
    gender: "male",
    category: "idol",
    keywords: ["밝은 에너지", "순수", "반전매력"],
    features: { eyes: "웃는 눈", nose: "자연스러운 코", lips: "자연스러운 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🎤",
  },
  hyunjin: {
    id: "hyunjin",
    name: "현진",
    group: "스트레이키즈",
    gender: "male",
    category: "idol",
    keywords: ["4세대 비주얼 원탑", "조각 같은", "예술가"],
    features: { eyes: "날카로운 눈매", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "🎭",
  },
  felix: {
    id: "felix",
    name: "펠릭스",
    group: "스트레이키즈",
    gender: "male",
    category: "idol",
    keywords: ["주근깨", "인형 비주얼", "저음 보이스"],
    features: { eyes: "큰 눈", nose: "작은 코", lips: "자연스러운 입술", faceShape: "작은 동그란 얼굴" },
    imageEmoji: "✨",
  },
  yeonjun: {
    id: "yeonjun",
    name: "연준",
    group: "투모로우바이투게더",
    gender: "male",
    category: "idol",
    keywords: ["패셔니스타", "시크", "카리스마"],
    features: { eyes: "날카로운 눈매", nose: "높은 코", lips: "도톰한 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🧢",
  },
  soobin: {
    id: "soobin",
    name: "수빈",
    group: "투모로우바이투게더",
    gender: "male",
    category: "idol",
    keywords: ["키 큰 리더", "보조개", "순수"],
    features: { eyes: "웃는 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🫧",
  },
  jake: {
    id: "jake",
    name: "제이크",
    group: "엔하이픈",
    gender: "male",
    category: "idol",
    keywords: ["강아지상", "밝은 미소", "따뜻한"],
    features: { eyes: "웃는 눈", nose: "자연스러운 코", lips: "자연스러운 입술", faceShape: "동그란 얼굴" },
    imageEmoji: "🐶",
  },
  sunghoon: {
    id: "sunghoon",
    name: "성훈",
    group: "엔하이픈",
    gender: "male",
    category: "idol",
    keywords: ["피겨왕자", "시크", "차가운 미남"],
    features: { eyes: "시크한 눈매", nose: "높은 코", lips: "얇은 입술", faceShape: "작은 V라인" },
    imageEmoji: "⛸️",
  },
  baekhyun: {
    id: "baekhyun",
    name: "백현",
    group: "EXO",
    gender: "male",
    category: "idol",
    keywords: ["강아지상", "밝은 에너지", "보이스 왕"],
    features: { eyes: "초승달 눈웃음", nose: "작은 코", lips: "자연스러운 입술", faceShape: "작은 얼굴" },
    imageEmoji: "🎵",
  },
  sehun: {
    id: "sehun",
    name: "세훈",
    group: "EXO",
    gender: "male",
    category: "idol",
    keywords: ["시크", "조각미남", "도시적"],
    features: { eyes: "날카로운 눈매", nose: "높은 콧대", lips: "얇은 입술", faceShape: "작은 갸름한 얼굴" },
    imageEmoji: "🏙️",
  },
  kai: {
    id: "kai",
    name: "카이",
    group: "EXO",
    gender: "male",
    category: "idol",
    keywords: ["섹시", "무대 장인", "강렬한"],
    features: { eyes: "깊은 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "💃",
  },
  taemin: {
    id: "taemin",
    name: "태민",
    group: "샤이니",
    gender: "male",
    category: "idol",
    keywords: ["중성적 매력", "천재 댄서", "신비로운"],
    features: { eyes: "날카로운 눈매", nose: "오똑한 코", lips: "얇은 입술", faceShape: "작은 V라인" },
    imageEmoji: "🌙",
  },
  minho: {
    id: "minho",
    name: "민호",
    group: "샤이니",
    gender: "male",
    category: "idol",
    keywords: ["불타는 카리스마", "남성미", "운동신경"],
    features: { eyes: "또렷한 눈", nose: "높은 콧대", lips: "자연스러운 입술", faceShape: "각진 턱선" },
    imageEmoji: "⚽",
  },
  taehyung: {
    id: "taehyung",
    name: "태형",
    group: "빅뱅",
    gender: "male",
    category: "idol",
    keywords: ["패션 아이콘", "독특한 매력", "카리스마"],
    features: { eyes: "날카로운 눈매", nose: "높은 코", lips: "얇은 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🎩",
  },

  /* ===== Male Actors (20) ===== */
  gongyoo: {
    id: "gongyoo",
    name: "공유",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["따뜻한 남자", "아저씨 매력", "깊은 눈빛"],
    features: { eyes: "따뜻한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "각진 얼굴" },
    imageEmoji: "☕",
  },
  hyunbin: {
    id: "hyunbin",
    name: "현빈",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["조각미남", "럭셔리", "남성적"],
    features: { eyes: "깊은 눈", nose: "높은 콧대", lips: "도톰한 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🤵",
  },
  wonbin: {
    id: "wonbin",
    name: "원빈",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["전설의 미남", "청순+남성미", "은퇴 미남"],
    features: { eyes: "또렷한 눈", nose: "완벽한 코", lips: "자연스러운 입술", faceShape: "작은 V라인" },
    imageEmoji: "👤",
  },
  kangdongwon: {
    id: "kangdongwon",
    name: "강동원",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["조각미남", "긴 얼굴", "시크"],
    features: { eyes: "시크한 눈매", nose: "높은 콧대", lips: "얇은 입술", faceShape: "긴 갸름한 얼굴" },
    imageEmoji: "🗿",
  },
  songjungki: {
    id: "songjungki",
    name: "송중기",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["귀공자", "깨끗한 이미지", "동안"],
    features: { eyes: "또렷한 눈", nose: "오똑한 코", lips: "자연스러운 입술", faceShape: "작은 계란형" },
    imageEmoji: "⚔️",
  },
  leeminho: {
    id: "leeminho",
    name: "이민호",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["한류 대표", "키큰 미남", "왕자 매력"],
    features: { eyes: "시원한 눈매", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "👑",
  },
  parkseojun: {
    id: "parkseojun",
    name: "박서준",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["남자친구상", "따뜻한 비주얼", "다정한"],
    features: { eyes: "따뜻한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "각진 턱선" },
    imageEmoji: "🤗",
  },
  kimsuhyun: {
    id: "kimsuhyun",
    name: "김수현",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["연기천재", "깊은 눈빛", "몰입형 배우"],
    features: { eyes: "깊은 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🎬",
  },
  parkbogeom: {
    id: "parkbogeom",
    name: "박보검",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["인간 비타민", "밝은 미소", "국민남친"],
    features: { eyes: "눈웃음", nose: "자연스러운 코", lips: "따뜻한 미소", faceShape: "부드러운 곡선" },
    imageEmoji: "😊",
  },
  songkang: {
    id: "songkang",
    name: "송강",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["인간 만화", "훈훈한", "달달한"],
    features: { eyes: "큰 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "📖",
  },
  namjoohyuk: {
    id: "namjoohyuk",
    name: "남주혁",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["모델 출신", "시크+따뜻", "키큰"],
    features: { eyes: "날카로운 눈매", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "📸",
  },
  leejongseok: {
    id: "leejongseok",
    name: "이종석",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["청순남", "도톰한 입술", "모델 출신"],
    features: { eyes: "부드러운 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🌤️",
  },
  seokangjun: {
    id: "seokangjun",
    name: "서강준",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["강아지상", "깨끗한 비주얼", "청순남"],
    features: { eyes: "맑은 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "작은 V라인" },
    imageEmoji: "🐕",
  },
  leedongwook: {
    id: "leedongwook",
    name: "이동욱",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["요정미남", "잔망", "동안"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🧚",
  },
  kimwoobin: {
    id: "kimwoobin",
    name: "김우빈",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["야성미", "카리스마", "모델 출신"],
    features: { eyes: "날카로운 눈매", nose: "높은 콧대", lips: "얇은 입술", faceShape: "긴 갸름한 얼굴" },
    imageEmoji: "🐺",
  },
  junghaein: {
    id: "junghaein",
    name: "정해인",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["따뜻한 미소", "선한 눈", "남자친구상"],
    features: { eyes: "따뜻한 눈", nose: "자연스러운 코", lips: "자연스러운 입술", faceShape: "부드러운 곡선" },
    imageEmoji: "🌿",
  },
  anhyoseop: {
    id: "anhyoseop",
    name: "안효섭",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["훈남", "조각미남", "달달한"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "작은 V라인" },
    imageEmoji: "💕",
  },
  byeonwooseok: {
    id: "byeonwooseok",
    name: "변우석",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["떠오르는 신예", "청량", "키큰"],
    features: { eyes: "시원한 눈매", nose: "높은 코", lips: "자연스러운 입술", faceShape: "갸름한 얼굴" },
    imageEmoji: "🚀",
  },
  rowoon: {
    id: "rowoon",
    name: "로운",
    group: "SF9/배우",
    gender: "male",
    category: "actor",
    keywords: ["만화 찢고 나온", "키큰", "완벽 비율"],
    features: { eyes: "또렷한 큰 눈", nose: "높은 코", lips: "도톰한 입술", faceShape: "작은 V라인" },
    imageEmoji: "📏",
  },
  hwanginyoup: {
    id: "hwanginyoup",
    name: "황인엽",
    group: "배우",
    gender: "male",
    category: "actor",
    keywords: ["사극미남", "4세대 배우", "남성미"],
    features: { eyes: "또렷한 눈", nose: "높은 코", lips: "자연스러운 입술", faceShape: "각진 턱선" },
    imageEmoji: "🏯",
  },
};

/* ==================== Carousel Names ==================== */
export const CELEBRITY_NAMES_CAROUSEL: string[] = [
  "카리나", "윈터", "제니", "지수", "로제", "리사", "나연", "사나", "쯔위",
  "안유진", "장원영", "민지", "하니", "해린", "아이린", "츄", "류진", "예지",
  "아이유", "수지", "한소희", "김태리", "전지현", "송혜교",
  "뷔", "정국", "차은우", "재현", "현진", "연준",
  "공유", "현빈", "원빈", "강동원", "송중기", "이민호",
  "박서준", "김수현", "박보검", "송강", "변우석", "로운",
  "미연", "우기", "사쿠라", "카즈하", "김채원", "허윤진",
  "백현", "세훈", "카이", "태민", "펠릭스", "성훈",
  "김지원", "김고은", "박보영", "신세경", "손예진",
  "남주혁", "이종석", "김우빈", "안효섭", "황인엽",
];

/* ==================== Loading Comments ==================== */
export const LOADING_COMMENTS: string[] = [
  "오... 이 얼굴은 연예인급인데요?",
  "눈매가 특별하시네요..!",
  "혹시 연예인 아니세요? 🤔",
  "이 조합은 처음 보는데... 대박!",
  "AI가 흥분하고 있어요 😆",
  "데이터베이스 풀가동 중!",
  "닮은꼴이 여러 명 나오네요!",
  "이 비율은 정말 특별해요...",
  "분위기가 독보적이시네요!",
  "결과가 나오면 놀라실 수도... 👀",
  "연예인 느낌이 강하게 나와요!",
  "매력 포인트를 찾았어요!",
];

/* ==================== Analysis Steps ==================== */
export const ANALYSIS_STEPS: string[] = [
  "얼굴 윤곽 스캔 중...",
  "눈/코/입 특징 분석 중...",
  "60+ 연예인 DB 대조 중...",
  "닮은꼴 매칭 계산 중...",
  "분위기 & 스타일 분석 중...",
  "최종 결과 생성 중...",
];
