import type { QuizConfig } from "../components/QuizEngine";

export const quizConfig: QuizConfig = {
  id: "dubai-cookie",
  emoji: "🍪",
  mainTitle: "나는 어떤",
  highlight: "두쫀쿠",
  subtitle: ["요즘 핫한 두바이 쫀득 쿠키로", "알아보는 내 성격 테스트!"],
  otherTests: [
    { emoji: "🍡", title: "나는 어떤 탕후루?", desc: "COMING SOON" },
    { emoji: "☕", title: "나는 어떤 카페 음료?", desc: "COMING SOON" },
    { emoji: "🍙", title: "나는 어떤 편의점 디저트?", desc: "COMING SOON" },
  ],
  questions: [
    {
      question: "주말에 나는 보통...",
      answers: [
        { text: "새로 뜬 핫플 탐방하기 🗺️", type: "matcha" },
        { text: "친구들이랑 왁자지껄 놀기 🎉", type: "strawberry" },
        { text: "넷플릭스 정주행 + 간식 폭격 🍿", type: "nutella" },
        { text: "조용한 카페에서 나만의 시간 ☕", type: "heugimja" },
      ],
    },
    {
      question: "친구들 사이에서 내 포지션은?",
      answers: [
        { text: "분위기 메이커! 내가 없으면 조용 🎤", type: "strawberry" },
        { text: "묵묵한 해결사, 다들 나한테 물어봄 🛠️", type: "original" },
        { text: "감성 담당, 추천은 나에게 맡겨 🎬", type: "tiramisu" },
        { text: "겉으론 조용한데 단톡방에선 드립왕 😎", type: "cookies_cream" },
      ],
    },
    {
      question: "내가 제일 좋아하는 음료는?",
      answers: [
        { text: "진~한 아메리카노 ☕", type: "heugimja" },
        { text: "달달한 카페라떼 🥛", type: "nutella" },
        { text: "상큼한 과일 스무디 🍹", type: "strawberry" },
        { text: "요즘 핫한 말차 라떼 🍵", type: "matcha" },
      ],
    },
    {
      question: "여행 간다면 내 스타일은?",
      answers: [
        { text: "분 단위 계획표 짜는 완벽주의자 📋", type: "original" },
        { text: "핫플·맛집 위주로 동선 짜기 📍", type: "matcha" },
        { text: "즉흥! 발길 닿는 대로~ 🌊", type: "lotus" },
        { text: "분위기 좋은 곳에서 여유롭게 ✨", type: "tiramisu" },
      ],
    },
    {
      question: "내가 듣고 싶은 칭찬은?",
      answers: [
        { text: '"너 진짜 멋있다" 😏', type: "cookies_cream" },
        { text: '"너 진짜 재밌어ㅋㅋ" 😂', type: "lotus" },
        { text: '"너 센스 뭐야" 🤩', type: "matcha" },
        { text: '"너 있으면 편해" 🤗', type: "nutella" },
      ],
    },
    {
      question: "내 옷장에 가장 많은 건?",
      answers: [
        { text: "올 블랙 컬렉션 🖤", type: "cookies_cream" },
        { text: "파스텔·화사한 컬러들 🌸", type: "strawberry" },
        { text: "베이지·크림 뉴트럴톤 🤎", type: "original" },
        { text: "다양한 컬러, 매일 다른 스타일 🌈", type: "lotus" },
      ],
    },
    {
      question: "스트레스 받으면 나는?",
      answers: [
        { text: "맛있는 거 먹으면서 해소! 🍰", type: "nutella" },
        { text: "쇼핑 or 새로운 거 시도 🛍️", type: "matcha" },
        { text: "혼자 조용히 충전 시간 🔋", type: "heugimja" },
        { text: "친구한테 전화해서 수다 폭발 📱", type: "strawberry" },
      ],
    },
    {
      question: "첫인상 vs 실제 나는?",
      answers: [
        { text: "거의 같음! 솔직한 게 내 매력 😊", type: "original" },
        { text: "차가워 보이지만 알면 따뜻 🧊→🔥", type: "cookies_cream" },
        { text: "조용해 보이지만 친해지면 미친텐션 🔥", type: "lotus" },
        { text: "밝아 보이지만 의외로 생각 깊음 🌙", type: "tiramisu" },
      ],
    },
    {
      question: "SNS에서 나는?",
      answers: [
        { text: "감성 피드 큐레이션 장인 📸", type: "tiramisu" },
        { text: "밈·드립 저장소, 남들 웃기는 게 낙 🤣", type: "lotus" },
        { text: "스토리 폭격기! 일상 공유 좋아 📱", type: "strawberry" },
        { text: "잠수 타다가 가끔 등장하는 미스터리 🕶️", type: "heugimja" },
      ],
    },
    {
      question: "나의 연애 스타일은?",
      answers: [
        { text: "밀당 같은 거 없이 진심으로 💝", type: "original" },
        { text: "츤데레... 좋아하는데 표현 못 함 💜", type: "cookies_cream" },
        { text: "다정다감 애정표현 폭발형 💗", type: "nutella" },
        { text: "분위기로 승부, 은은한 매력 어필 🌹", type: "tiramisu" },
      ],
    },
  ],
  results: {
    original: {
      emoji: "🍫",
      name: "오리지널 두쫀쿠",
      color: "#B8860B",
      bgClass: "from-amber-100 via-orange-50 to-yellow-50",
      bgStart: "#FEF3C7",
      bgEnd: "#FEFCE8",
      title: "클래식은 이유가 있는 법 ✨",
      description:
        "피스타치오 크림에 바삭한 카다이프...\n정석이 정석인 이유, 바로 당신 같은 사람이 있기 때문!\n\n유행 타지 않는 변함없는 매력으로\n사람들이 결국 돌고 돌아 찾게 되는\n어디서든 믿고 보는 '인생 원픽' 같은 존재예요.",
      shortDesc: "변함없는 매력의 클래식 인간",
      tags: ["#원조가_원조인_이유", "#믿고보는_인간", "#돌고돌아_나"],
      bestMatch: "🍓 딸기 두쫀쿠",
      funMatch: "🖤 쿠앤크 두쫀쿠",
    },
    cookies_cream: {
      emoji: "🖤",
      name: "쿠앤크 두쫀쿠",
      color: "#2D2B55",
      bgClass: "from-slate-100 via-purple-50 to-indigo-50",
      bgStart: "#F1F5F9",
      bgEnd: "#EEF2FF",
      title: "겉쿨속진, 반전매력 치명적 💜",
      description:
        "겉은 쿨~하고 시크한데\n알고 보면 세상 다정하고 진한 사람!\n\n쉽게 속을 보여주지 않지만\n한번 마음 열면 누구보다 깊고 진해서\n상대를 홀려버리는 치명적인 타입.",
      shortDesc: "겉은 쿨, 속은 진한 반전 인간",
      tags: ["#겉쿨속진", "#반전매력_끝판왕", "#알면빠짐"],
      bestMatch: "🍫 오리지널 두쫀쿠",
      funMatch: "🍓 딸기 두쫀쿠",
    },
    strawberry: {
      emoji: "🍓",
      name: "딸기 두쫀쿠",
      color: "#E91E7B",
      bgClass: "from-pink-100 via-rose-50 to-red-50",
      bgStart: "#FCE7F3",
      bgEnd: "#FEF2F2",
      title: "어딜 가나 분위기 핑크빛 🌸",
      description:
        "당신이 있으면 분위기가 화사해지고\n당신이 없으면 뭔가 허전한,\n그런 사랑스러운 존재!\n\n밝은 에너지로 모두의 기분을\n업시켜주는 인기 만점 분위기 메이커.",
      shortDesc: "분위기를 핑크빛으로 물들이는 인간",
      tags: ["#무드메이커", "#인기쟁이", "#에너지_뿜뿜"],
      bestMatch: "🍫 오리지널 두쫀쿠",
      funMatch: "🍵 말차 두쫀쿠",
    },
    matcha: {
      emoji: "🍵",
      name: "말차 두쫀쿠",
      color: "#2E7D32",
      bgClass: "from-green-100 via-emerald-50 to-teal-50",
      bgStart: "#DCFCE7",
      bgEnd: "#F0FDFA",
      title: "트렌드는 내가 만든다 🌿",
      description:
        "핫플은 내가 먼저 가고\n유행은 내가 먼저 시작하는 사람!\n\n남들과 다른 독특한 취향과\n확실한 자기만의 감성으로\n주변 사람들의 워너비가 되는 힙스터.",
      shortDesc: "취향 확실한 트렌드세터 인간",
      tags: ["#힙스터", "#트렌드세터", "#취향_존중해"],
      bestMatch: "🧁 로투스 두쫀쿠",
      funMatch: "🍠 흑임자 두쫀쿠",
    },
    nutella: {
      emoji: "🥜",
      name: "누텔라 두쫀쿠",
      color: "#6D4C2E",
      bgClass: "from-orange-100 via-amber-50 to-yellow-50",
      bgStart: "#FFEDD5",
      bgEnd: "#FEFCE8",
      title: "한번 빠지면 못 나오는 중독성 🤎",
      description:
        "진하고 달콤한 매력으로\n한번 친해지면 절대 떠날 수 없게 만드는 사람!\n\n따뜻하고 다정한 성격에\n함께 있으면 마음이 포근해지는\n인간 핫초코 같은 존재.",
      shortDesc: "한번 빠지면 헤어나올 수 없는 인간",
      tags: ["#인간_핫초코", "#다정_폭발", "#중독주의보"],
      bestMatch: "🍠 흑임자 두쫀쿠",
      funMatch: "🌰 티라미수 두쫀쿠",
    },
    lotus: {
      emoji: "🧁",
      name: "로투스 두쫀쿠",
      color: "#C2703E",
      bgClass: "from-orange-100 via-yellow-50 to-amber-50",
      bgStart: "#FFEDD5",
      bgEnd: "#FFFBEB",
      title: "호불호 없는 만능 인기인 ⭐",
      description:
        "달콤하면서도 짭짤한 절묘한 매력!\n누구에게나 잘 맞는 팔방미인 타입.\n\n특유의 유머와 개성으로\n어떤 그룹에서든 자연스럽게 어울리며\n모두에게 사랑받는 인싸 중의 인싸!",
      shortDesc: "어디서든 사랑받는 만능 인간",
      tags: ["#팔방미인", "#인싸_중_인싸", "#호불호_제로"],
      bestMatch: "🍵 말차 두쫀쿠",
      funMatch: "🍫 오리지널 두쫀쿠",
    },
    heugimja: {
      emoji: "🍠",
      name: "흑임자 두쫀쿠",
      color: "#4A4A4A",
      bgClass: "from-stone-200 via-gray-100 to-neutral-50",
      bgStart: "#E7E5E4",
      bgEnd: "#FAFAFA",
      title: "알수록 빠져드는 깊은 매력 🌑",
      description:
        "고소하고 묵직한 매력의 소유자!\n처음엔 조용해 보이지만\n알면 알수록 빠져드는 깊이가 있는 사람.\n\n자기만의 세계가 확실하고\n혼자만의 시간을 즐길 줄 아는\n성숙하고 매력적인 어른.",
      shortDesc: "깊은 매력의 성숙한 인간",
      tags: ["#고소한_매력", "#어른의_깊이", "#알수록_빠짐"],
      bestMatch: "🥜 누텔라 두쫀쿠",
      funMatch: "🧁 로투스 두쫀쿠",
    },
    tiramisu: {
      emoji: "🌰",
      name: "티라미수 두쫀쿠",
      color: "#7B5B3A",
      bgClass: "from-amber-100 via-stone-50 to-orange-50",
      bgStart: "#FEF3C7",
      bgEnd: "#FFF7ED",
      title: "은은하게 취하게 만드는 무드 🍷",
      description:
        "고급지고 우아한 분위기를 풍기는 당신!\n과하지 않은 은은한 매력으로\n사람들을 자연스럽게 끌어당기는 타입.\n\n센스 있고 감성적인 성격으로\n함께 있으면 왠지 모르게 설레는\n분위기 장인.",
      shortDesc: "은은한 매력의 분위기 장인",
      tags: ["#분위기_장인", "#고급_감성", "#은은한_치명"],
      bestMatch: "🖤 쿠앤크 두쫀쿠",
      funMatch: "🥜 누텔라 두쫀쿠",
    },
  },
};
