/* ==================== Animal Face Types ==================== */

export interface AnimalType {
  id: string;
  emoji: string;
  name: string;
  color: string;
  bgStart: string;
  bgEnd: string;
  personality: string;
  loveStyle: string;
  strengths: string[];
  weaknesses: string[];
  bestMatch: string;
  funMatch: string;
  celebrities: string[];
  shortDesc: string;
  tags: string[];
}

export const animalTypes: Record<string, AnimalType> = {
  dog: {
    id: "dog",
    emoji: "🐶",
    name: "강아지상",
    color: "#F59E0B",
    bgStart: "#FEF3C7",
    bgEnd: "#FFFBEB",
    personality:
      "순수하고 활발한 에너지의 소유자!\n누구에게나 호감을 주는 따뜻한 사람이에요.\n충성스럽고 애교 많은 당신,\n함께 있으면 절대 지루하지 않아요!",
    loveStyle: "직진적이고 애정표현 폭발형! 좋으면 온 몸으로 표현해요.",
    strengths: ["충성스러움", "밝은 에너지", "사교성", "순수함"],
    weaknesses: ["질투심", "분리불안", "참을성 부족"],
    bestMatch: "🐱 고양이상",
    funMatch: "🦊 여우상",
    celebrities: ["박보검", "수지(배우)", "차은우"],
    shortDesc: "순수하고 충성스러운 인간 강아지",
    tags: ["#애교만점", "#충성_MAX", "#인간_비타민"],
  },
  cat: {
    id: "cat",
    emoji: "🐱",
    name: "고양이상",
    color: "#8B5CF6",
    bgStart: "#EDE9FE",
    bgEnd: "#F5F3FF",
    personality:
      "독립적이고 신비로운 매력의 소유자!\n쉽게 마음을 열지 않지만\n한번 허락하면 세상 다정한 사람.\n그 반전 매력이 치명적이에요!",
    loveStyle: "츠데레 스타일. 좋아하지만 티 안 내다가 문득 표현해요.",
    strengths: ["독립성", "센스", "미적 감각", "자기관리"],
    weaknesses: ["낯가림", "변덕스러움", "경계심"],
    bestMatch: "🐶 강아지상",
    funMatch: "🐻 곰상",
    celebrities: ["장원영", "제니(블핑)", "한소희"],
    shortDesc: "신비로운 반전매력의 독립적 인간",
    tags: ["#츠데레", "#내_갈길_내가_간다", "#반전매력"],
  },
  fox: {
    id: "fox",
    emoji: "🦊",
    name: "여우상",
    color: "#EA580C",
    bgStart: "#FFEDD5",
    bgEnd: "#FFF7ED",
    personality:
      "영리하고 매력적인 분위기 메이커!\n상황 파악이 빠르고 센스 있는 행동으로\n사람들의 마음을 사로잡는 타입.\n모든 걸 다 가진 팔방미인!",
    loveStyle: "전략적 연애가. 밀당의 고수이지만 진심을 보이면 헌신적.",
    strengths: ["사교성", "순발력", "영리함", "유머"],
    weaknesses: ["계산적", "질림", "경쟁심"],
    bestMatch: "🐺 늑대상",
    funMatch: "🐶 강아지상",
    celebrities: ["송지효", "정해인", "한예슬"],
    shortDesc: "영리하고 매력적인 분위기 메이커",
    tags: ["#센스만점", "#분위기_장인", "#팔방미인"],
  },
  bear: {
    id: "bear",
    emoji: "🐻",
    name: "곰상",
    color: "#92400E",
    bgStart: "#FDE68A",
    bgEnd: "#FEF9C3",
    personality:
      "포근하고 든든한 인간 인형 비타민!\n큰 체격에 부드러운 마음을 가졌어요.\n느릿해 보이지만 중요한 순간에는\n누구보다 든든하게 지켜주는 사람!",
    loveStyle: "포용력 만점! 큰 품으로 모든 걸 감싸주는 스타일.",
    strengths: ["포용력", "신뢰감", "든든함", "인내심"],
    weaknesses: ["느림", "우유부단", "고집"],
    bestMatch: "🐰 토끼상",
    funMatch: "🐱 고양이상",
    celebrities: ["마동석", "강하닐", "조세호"],
    shortDesc: "포근하고 든든한 인간 인형 비타민",
    tags: ["#인간_인형비타민", "#포용력_MAX", "#든든"],
  },
  rabbit: {
    id: "rabbit",
    emoji: "🐰",
    name: "토끼상",
    color: "#EC4899",
    bgStart: "#FCE7F3",
    bgEnd: "#FDF2F8",
    personality:
      "사랑스럽고 귀여운 매력의 소유자!\n부드럽고 순수한 외모와 달리\n의외로 또띻한 면도 있는 반전 매력!\n주변 사람들을 힘빠지게 하는 존재에요.",
    loveStyle: "설렘을 주는 매력의 소유자. 애교와 애정표현으로 상대를 붙잡아요.",
    strengths: ["귀여움", "적응력", "사교성", "긍정성"],
    weaknesses: ["소심", "걸정이 많음", "우유부단"],
    bestMatch: "🐻 곰상",
    funMatch: "🦉 부엉이상",
    celebrities: ["아이유", "아린", "배수지"],
    shortDesc: "사랑스럽고 귀여운 반전 매력 인간",
    tags: ["#귀여움_폭발", "#순수함_만점", "#반전매력"],
  },
  deer: {
    id: "deer",
    emoji: "🦌",
    name: "사슴상",
    color: "#059669",
    bgStart: "#D1FAE5",
    bgEnd: "#ECFDF5",
    personality:
      "우아하고 기품 있는 분위기의 소유자!\n조용하지만 강한 존재감으로\n자연스럽게 시선을 사로잡는 타입.\n순수하면서도 지적인 매력!",
    loveStyle: "순수하고 로맨틱한 연애를 꿈꾸는 타입.",
    strengths: ["우아함", "지적 매력", "성실함", "차분함"],
    weaknesses: ["소극성", "경계심", "기죽이 살지 않음"],
    bestMatch: "🦊 여우상",
    funMatch: "🐧 펭귄상",
    celebrities: ["수지(블핑)", "차은우", "박보검"],
    shortDesc: "우아하고 기품 있는 순수한 인간",
    tags: ["#우아함_끝판왕", "#은은한_치명", "#기품_있는"],
  },
  dino: {
    id: "dino",
    emoji: "🦕",
    name: "공룡상",
    color: "#16A34A",
    bgStart: "#DCFCE7",
    bgEnd: "#F0FDF4",
    personality:
      "엉뜻하고 순수한 매력의 소유자!\n자기만의 세계가 확실하고\n독특한 감성으로 사람들을 사로잡아요.\n예측불가한 행동이 매력 포인트!",
    loveStyle: "순수하고 직진적! 좋아하면 다 티가 나는 타입.",
    strengths: ["독특함", "창의성", "순수함", "마이페이스"],
    weaknesses: ["엉뜻함", "눈치 없음", "고집"],
    bestMatch: "🐹 햄스터상",
    funMatch: "🐯 호랑이상",
    celebrities: ["박보검", "이광수", "송강"],
    shortDesc: "엉뜻하고 독특한 감성의 순수 인간",
    tags: ["#엉뜻미", "#나만의_세계", "#예측불가"],
  },
  wolf: {
    id: "wolf",
    emoji: "🐺",
    name: "늑대상",
    color: "#475569",
    bgStart: "#E2E8F0",
    bgEnd: "#F1F5F9",
    personality:
      "카리스마 넘치는 야성의 매력!\n과묵하지만 속에서는 뜨거운 열정이 타오르는,\n강하고 매력적인 리더 타입.\n한번 마음을 주면 끝까지 지켜주는 사람!",
    loveStyle: "직진적이고 보호본능이 강한 타입. 사랑하면 목숨 걸어요.",
    strengths: ["리더십", "카리스마", "의리", "결단력"],
    weaknesses: ["지배욕", "경쟁심", "고집"],
    bestMatch: "🦊 여우상",
    funMatch: "🐰 토끼상",
    celebrities: ["현빈", "차은우", "비(빅벡)"],
    shortDesc: "카리스마 넘치는 강하고 매력적인 리더",
    tags: ["#야성미", "#카리스마_폭발", "#의리의_사람"],
  },
  penguin: {
    id: "penguin",
    emoji: "🐧",
    name: "펭귄상",
    color: "#0EA5E9",
    bgStart: "#E0F2FE",
    bgEnd: "#F0F9FF",
    personality:
      "귀엽고 유머러운 무드 메이커!\n뒤뛱거리며 돌아다니는 모습이 매력적이고\n함께 있으면 자연스럽게 웃음이 나와요.\n의외로 고집이 세고 인내심이 강해요!",
    loveStyle: "헌신적이고 순정파! 한번 사랑하면 오래 가는 타입.",
    strengths: ["유머", "인내심", "성실함", "단체생활"],
    weaknesses: ["느림", "소심함", "변화 부담"],
    bestMatch: "🦕 공룡상",
    funMatch: "🦌 사슴상",
    celebrities: ["변우석", "카리나", "유재석"],
    shortDesc: "귀엽고 유머러운 인간 무드 메이커",
    tags: ["#귀여움_폭발", "#인내심_끝판", "#유머만점"],
  },
  owl: {
    id: "owl",
    emoji: "🦉",
    name: "부엉이상",
    color: "#7C3AED",
    bgStart: "#EDE9FE",
    bgEnd: "#FAF5FF",
    personality:
      "지적이고 통찰력 있는 현자 타입!\n조용하지만 모든 걸 꾽꾽히 생각하고\n핵심을 정확히 짚어내는 능력자.\n신비로운 분위기가 매력 포인트!",
    loveStyle: "지적 대화를 중시하고, 깊은 연결을 추구하는 타입.",
    strengths: ["지혜", "통찰력", "집중력", "냉정함"],
    weaknesses: ["완벽주의", "소통 부족", "고립감"],
    bestMatch: "🐰 토끼상",
    funMatch: "🦕 공룡상",
    celebrities: ["백현", "조승우", "아이유"],
    shortDesc: "지적이고 통찰력 있는 신비로운 현자",
    tags: ["#인간_현자", "#통찰력_MAX", "#신비로운"],
  },
  hamster: {
    id: "hamster",
    emoji: "🐹",
    name: "햄스터상",
    color: "#F97316",
    bgStart: "#FFF7ED",
    bgEnd: "#FFFBEB",
    personality:
      "작고 귀여운 매력으로 모두의 사랑을 받는 타입!\n부지런하고 열정적이며\n먹는 것을 좋아하는 귀여운 미식가.\n항상 바쁘게 움직이는 에너지!",
    loveStyle: "애교 폭발형! 사랑하면 온몸으로 표현하는 타입.",
    strengths: ["귀여움", "부지런함", "열정", "긍정성"],
    weaknesses: ["참을성 부족", "소심함", "무계획"],
    bestMatch: "🦕 공룡상",
    funMatch: "🐻 곰상",
    celebrities: ["아린", "다현(모아)", "안유진"],
    shortDesc: "부지런하고 귀여운 인간 햄스터",
    tags: ["#부지런함", "#먹는게_제일좋아", "#귀여움_테러"],
  },
  tiger: {
    id: "tiger",
    emoji: "🐯",
    name: "호랑이상",
    color: "#DC2626",
    bgStart: "#FEE2E2",
    bgEnd: "#FEF2F2",
    personality:
      "강렬하고 자신감 넘치는 왕의 기질!\n어떤 상황에서도 도전을 두려워하지 않고\n자기 확신과 열정으로 목표를 향해 달려가는\n타고난 리더!",
    loveStyle: "직진적이고 화끄한 연애! 목표를 정하면 반드시 잡는 타입.",
    strengths: ["자신감", "리더십", "결단력", "열정"],
    weaknesses: ["과신", "성급함", "독선적"],
    bestMatch: "🐺 늑대상",
    funMatch: "🦕 공룡상",
    celebrities: ["손흥민", "제니(블핑)", "류현진"],
    shortDesc: "강렬하고 카리스마 넘치는 타고난 리더",
    tags: ["#왕의_기질", "#도전정신", "#자신감_폭발"],
  },
  dolphin: {
    id: "dolphin",
    emoji: "🐬",
    name: "돌고래상",
    color: "#0891B2",
    bgStart: "#CFFAFE",
    bgEnd: "#ECFEFF",
    personality: "똑똑하고 사교적인 인싸 중의 인싸!\n어디서든 분위기를 밝히고\n사람들과 즐겁게 어울리는 타입.\n유쾌한 에너지로 모두를 사로잡아요!",
    loveStyle: "함께 있으면 즐거운 베스트 프렌드형 연인. 같이 새로운 걸 경험하는 걸 좋아해요.",
    strengths: ["사교성", "유쾌함", "지적 매력", "적응력"],
    weaknesses: ["지루함 못 참음", "깊이 부족", "관심 필요"],
    bestMatch: "🦜 앵무새상",
    funMatch: "🦥 나무늘보상",
    celebrities: ["유재석", "전현무", "이효리"],
    shortDesc: "똑똑하고 유쾌한 바다의 인싸",
    tags: ["#인싸_of_인싸", "#유쾌함_폭발", "#사교왕"],
  },
  butterfly: {
    id: "butterfly",
    emoji: "🦋",
    name: "나비상",
    color: "#D946EF",
    bgStart: "#FAE8FF",
    bgEnd: "#FDF4FF",
    personality: "자유롭고 아름다운 영혼의 소유자!\n한곳에 머무르지 않고\n새로운 세계를 탐험하며 살아가는 타입.\n변화를 두려워하지 않는 용기가 매력!",
    loveStyle: "자유로운 영혼이라 구속을 싫어해요. 서로의 공간을 존중하는 연애를 원해요.",
    strengths: ["자유로움", "적응력", "심미안", "변화를 즐김"],
    weaknesses: ["변덕", "정착 어려움", "깊이 부족"],
    bestMatch: "🐺 늑대상",
    funMatch: "🐬 돌고래상",
    celebrities: ["제니(블핑)", "GD", "설리"],
    shortDesc: "자유롭고 아름다운 영혼의 탐험가",
    tags: ["#자유영혼", "#변화를_즐기는", "#아름다운_존재"],
  },
  squirrel: {
    id: "squirrel",
    emoji: "🐿️",
    name: "다람쥐상",
    color: "#D97706",
    bgStart: "#FEF3C7",
    bgEnd: "#FFFBEB",
    personality: "부지런하고 알뜰한 준비왕!\n항상 미래를 대비하고 계획하는\n철저한 성격의 소유자.\n작지만 강한 에너지로 목표를 이뤄내요!",
    loveStyle: "계획적이고 안정적인 연애를 추구. 기념일도 절대 안 잊어버려요.",
    strengths: ["부지런함", "계획성", "알뜰함", "실행력"],
    weaknesses: ["걱정 많음", "소심함", "욕심"],
    bestMatch: "🐻 곰상",
    funMatch: "🦕 공룡상",
    celebrities: ["아이유", "정해인", "박보영"],
    shortDesc: "부지런하고 알뜰한 완벽 준비왕",
    tags: ["#부지런함_MAX", "#알뜰살뜰", "#준비왕"],
  },
  sloth: {
    id: "sloth",
    emoji: "🦥",
    name: "나무늘보상",
    color: "#65A30D",
    bgStart: "#ECFCCB",
    bgEnd: "#F7FEE7",
    personality: "여유롭고 평화로운 힐링 존재!\n느긋하게 자기만의 속도로 살아가는\n마이페이스 타입.\n함께 있으면 마음이 편해지는 사람!",
    loveStyle: "느긋하고 편안한 연애. 서로 아무것도 안 해도 행복한 관계가 이상적.",
    strengths: ["여유로움", "평화로움", "스트레스 관리", "경청"],
    weaknesses: ["게으름", "결단력 부족", "느림"],
    bestMatch: "🐼 판다상",
    funMatch: "🐬 돌고래상",
    celebrities: ["공유", "카리나", "변우석"],
    shortDesc: "여유롭고 평화로운 힐링 인간",
    tags: ["#여유만만", "#마이페이스", "#힐링_존재"],
  },
  panda: {
    id: "panda",
    emoji: "🐼",
    name: "판다상",
    color: "#374151",
    bgStart: "#F3F4F6",
    bgEnd: "#F9FAFB",
    personality: "귀엽고 느긋한 먹보 매력의 소유자!\n먹는 걸 사랑하고 느긋하지만\n의외로 고집이 세고 자기 주관이 뚜렷해요.\n보기와 다른 반전 매력이 포인트!",
    loveStyle: "함께 맛있는 거 먹으면서 소소한 행복을 나누는 연애가 최고!",
    strengths: ["귀여움", "여유", "자기 주관", "반전 매력"],
    weaknesses: ["게으름", "고집", "무관심"],
    bestMatch: "🦥 나무늘보상",
    funMatch: "🐹 햄스터상",
    celebrities: ["송강", "안유진", "차은우"],
    shortDesc: "귀엽고 느긋한 반전 매력 먹보",
    tags: ["#먹보_매력", "#귀여운_반전", "#느긋함_끝판"],
  },
  parrot: {
    id: "parrot",
    emoji: "🦜",
    name: "앵무새상",
    color: "#0D9488",
    bgStart: "#CCFBF1",
    bgEnd: "#F0FDFA",
    personality: "밝고 수다스러운 에너지 폭탄!\n이야기하는 걸 좋아하고\n표현력이 뛰어난 엔터테이너 타입.\n어디서든 존재감이 빛나는 사람!",
    loveStyle: "대화가 중요! 말로 사랑을 표현하고 함께 이야기 나누는 걸 좋아해요.",
    strengths: ["표현력", "사교성", "밝은 에너지", "재치"],
    weaknesses: ["수다", "오지랖", "집중력 부족"],
    bestMatch: "🐬 돌고래상",
    funMatch: "🐱 고양이상",
    celebrities: ["이영지", "유재석", "장원영"],
    shortDesc: "밝고 수다스러운 인간 엔터테이너",
    tags: ["#수다왕", "#에너지_폭탄", "#표현력_만점"],
  },
};

/* ==================== Quiz Questions ==================== */

export interface QuizQuestion {
  question: string;
  answers: { text: string; scores: Record<string, number> }[];
}

export const quizQuestions: QuizQuestion[] = [
  {
    question: "친구들과 모임에서 나의 포지션은?",
    answers: [
      { text: "분위기 메이커! 내가 있으면 신난다 🎉", scores: { dog: 2, penguin: 1, fox: 1 } },
      { text: "조용히 관찰하다 핵심만 콕 짚어내는 타입 🧐", scores: { owl: 2, dino: 1, wolf: 1 } },
      { text: "모두를 챙기며 잘 맞춰주는 중재자 🤝", scores: { bear: 2, dolphin: 1, butterfly: 1 } },
      { text: "필요할 때 확실하게 리드하는 리더 👑", scores: { tiger: 2, squirrel: 1, panda: 1 } },
    ],
  },
  {
    question: "주말에 가장 하고 싶은 것은?",
    answers: [
      { text: "친구들이랑 신나게 놀고 싶어! 🎉", scores: { dog: 2, penguin: 1, bear: 1 } },
      { text: "집에서 혼자 조용히 쉬고 싶어 🛋️", scores: { cat: 2, owl: 1, parrot: 1 } },
      { text: "새로운 곳도 해보고 싶어! 🌟", scores: { fox: 2, dino: 1, wolf: 1 } },
      { text: "맛있는 거 먹으면서 산책하고 싶어 🌿", scores: { hamster: 2, dolphin: 1, butterfly: 1 } },
    ],
  },
  {
    question: "화가 났을 때 나의 반응은?",
    answers: [
      { text: "바로 표현한다! 화 참는 건 모해 🔥", scores: { tiger: 2, penguin: 1, bear: 1 } },
      { text: "내색하지 않지만 속으로 부글부글 😤", scores: { cat: 2, owl: 1, squirrel: 1 } },
      { text: "한발 물러서서 상황 판단 후 대응 🧐", scores: { fox: 2, panda: 1, parrot: 1 } },
      { text: "금방 풀림… 화를 오래 유지 못 함 😅", scores: { rabbit: 2, dog: 1, deer: 1 } },
    ],
  },
  {
    question: "첫인상 vs 실제 나는?",
    answers: [
      { text: "차가워 보이지만 알면 따뜻해 🧣→❤️", scores: { wolf: 2, fox: 1, cat: 1 } },
      { text: "거의 같음! 속과 겉이 똑같아 😄", scores: { dog: 2, bear: 1, rabbit: 1 } },
      { text: "조용해 보이지만 친해지면 미친 텐션 🔥", scores: { penguin: 2, dino: 1, hamster: 1 } },
      { text: "밝아 보이지만 의외로 생각이 깊음 🌙", scores: { owl: 2, tiger: 1, dolphin: 1 } },
    ],
  },
  {
    question: "연애할 때 나의 스타일은?",
    answers: [
      { text: "애교 폭발! 좋아하면 온 몸으로 표현 💕", scores: { rabbit: 2, penguin: 1, wolf: 1 } },
      { text: "쿨데레… 좋아하는데 표현 못 함 😳", scores: { deer: 2, owl: 1, butterfly: 1 } },
      { text: "밀당의 고수! 전략적으로 어필 🎯", scores: { fox: 2, squirrel: 1, sloth: 1 } },
      { text: "진지하고 든든하게 오래 가는 연애 🥰", scores: { bear: 2, panda: 1, parrot: 1 } },
    ],
  },
  {
    question: "내 방의 분위기를 말한다면?",
    answers: [
      { text: "코지하고 아기자기한 사랑스러운 방 🧸", scores: { rabbit: 2, fox: 1, penguin: 1 } },
      { text: "미니멀하고 정돈된 깔끔한 방 🧹", scores: { deer: 2, dog: 1, cat: 1 } },
      { text: "취향을 반영한 독특한 인테리어 🎨", scores: { dino: 2, wolf: 1, owl: 1 } },
      { text: "편안함이 최고! 포근한 심플 방 🛋️", scores: { bear: 2, hamster: 1, tiger: 1 } },
    ],
  },
  {
    question: "SNS에서 나의 활동 스타일은?",
    answers: [
      { text: "일상 공유 + 스토리 폭방! 소통이 중요 📱", scores: { dolphin: 2, fox: 1, bear: 1 } },
      { text: "감성 피드 큐레이션 장인 📸", scores: { deer: 2, rabbit: 1, dino: 1 } },
      { text: "잠수 타다 가끔 밤에 등장 🌙", scores: { owl: 2, butterfly: 1, squirrel: 1 } },
      { text: "밈·드립 저장소, 웃기는 게 제일 좋아 🤣", scores: { penguin: 2, sloth: 1, panda: 1 } },
    ],
  },
  {
    question: "여행 간다면 나의 스타일은?",
    answers: [
      { text: "철저한 계획 + 완벽한 동선 📋", scores: { squirrel: 2, deer: 1, penguin: 1 } },
      { text: "즉흥으로! 발길 닿는 대로 🌊", scores: { dino: 2, dolphin: 1, parrot: 1 } },
      { text: "맛집 투어가 제일 중요! 먹방 여행 🍜", scores: { hamster: 2, dog: 1, cat: 1 } },
      { text: "여유롭게 분위기 좋은 곳에서 힐링 🌿", scores: { sloth: 2, fox: 1, bear: 1 } },
    ],
  },
  {
    question: "스트레스 받을 때 나만의 해소법은?",
    answers: [
      { text: "운동이나 산책으로 몸을 움직이기 🏃", scores: { wolf: 2, rabbit: 1, deer: 1 } },
      { text: "맛있는 거 먹으면서 뭔하게 보기 🍰", scores: { hamster: 2, dino: 1, penguin: 1 } },
      { text: "혼자 조용히 생각 정리하기 🧘", scores: { cat: 2, owl: 1, tiger: 1 } },
      { text: "친구한테 전화해서 수다 폭발 📞", scores: { parrot: 2, dolphin: 1, butterfly: 1 } },
    ],
  },
  {
    question: "내 인생 모토와 가장 가까운 것은?",
    answers: [
      { text: "\"인생은 즐기는 거야! 오늘을 즐기자\" 🎈", scores: { dog: 2, wolf: 1, hamster: 1 } },
      { text: "\"하는 만큼 된다. 목표를 향해 달려가자\" 🚀", scores: { tiger: 2, squirrel: 1, sloth: 1 } },
      { text: "\"나답게 살자. 남 눈치 보지 말고\" 🌟", scores: { butterfly: 2, parrot: 1, cat: 1 } },
      { text: "\"사람이 제일 중요해. 관계를 소중히\" 🤍", scores: { panda: 2, fox: 1, bear: 1 } },
    ],
  },
  {
    question: "친구가 고민을 이야기할 때 나의 반응은?",
    answers: [
      { text: "같이 울면서 공감해주는 타입 😢", scores: { rabbit: 2, dog: 1, deer: 1 } },
      { text: "바로 해결책을 제시해줌! 💡", scores: { tiger: 2, dino: 1, wolf: 1 } },
      { text: "맛있는 거 사주면서 기분 전환시켜줌 🍰", scores: { panda: 2, penguin: 1, owl: 1 } },
      { text: "조용히 옆에서 끝까지 들어주는 편 🤗", scores: { sloth: 2, hamster: 1, dolphin: 1 } },
    ],
  },
  {
    question: "나의 아침 루틴은?",
    answers: [
      { text: "알람 끄고 이불 속에서 뒹굴뒹굴 🛏️", scores: { sloth: 2, panda: 1, rabbit: 1 } },
      { text: "일어나자마자 계획대로 척척 ⏰", scores: { squirrel: 2, tiger: 1, butterfly: 1 } },
      { text: "음악 틀고 신나게 준비! 🎵", scores: { parrot: 2, dog: 1, cat: 1 } },
      { text: "일단 밥부터… 먹어야 힘이 나지 🍚", scores: { hamster: 2, fox: 1, bear: 1 } },
    ],
  },
  {
    question: "좋아하는 사람 앞에서 나는?",
    answers: [
      { text: "자꾸 쳐다보다 눈 마주치면 도망 👀", scores: { deer: 2, sloth: 1, panda: 1 } },
      { text: "자연스럽게 옆에 가서 말 걸기 😊", scores: { dolphin: 2, parrot: 1, rabbit: 1 } },
      { text: "모른 척하면서 은근히 신경 쓰기 😏", scores: { wolf: 2, dino: 1, penguin: 1 } },
      { text: "선물이나 음식으로 마음을 표현 🎁", scores: { squirrel: 2, owl: 1, hamster: 1 } },
    ],
  },
  {
    question: "단체 사진 찍을 때 나의 포지션은?",
    answers: [
      { text: "맨 앞에서 브이! 센터 좋아 ✌️", scores: { parrot: 2, squirrel: 1, deer: 1 } },
      { text: "구석에서 조용히 미소 짓기 🙂", scores: { cat: 2, wolf: 1, tiger: 1 } },
      { text: "장난치면서 웃긴 표정 짓기 🤪", scores: { dino: 2, dolphin: 1, sloth: 1 } },
      { text: "자연스럽게 포즈 잡는 스타일 💫", scores: { butterfly: 2, panda: 1, dog: 1 } },
    ],
  },
  {
    question: "갑자기 내일 휴가라면?",
    answers: [
      { text: "친구들한테 바로 연락! 같이 놀자 📱", scores: { dolphin: 2, squirrel: 1, parrot: 1 } },
      { text: "카페에서 혼자 책 읽으며 힐링 ☕", scores: { sloth: 2, cat: 1, fox: 1 } },
      { text: "먹고 싶었던 거 다 먹으러 가기 🍕", scores: { panda: 2, bear: 1, rabbit: 1 } },
      { text: "급 여행! 어디든 떠나자 ✈️", scores: { butterfly: 2, deer: 1, dino: 1 } },
    ],
  },
];
